import 'package:detoxia/core/constants/enums.dart';
import 'package:flutter/widgets.dart';

class ActivationActivity {
  final String id;
  final String title;
  final ActivityCategory category;
  final int durationMinutes;
  final String description;

  const ActivationActivity({
    required this.id,
    required this.title,
    required this.category,
    required this.durationMinutes,
    required this.description,
  });
}

const activityPool = <ActivationActivity>[
  // ─── Physical Activity ───
  ActivationActivity(
    id: 'pa_01',
    title: 'Take a 10-min walk',
    category: ActivityCategory.physicalActivity,
    durationMinutes: 10,
    description: 'Walk around your block or neighborhood at a comfortable pace.',
  ),
  ActivationActivity(
    id: 'pa_02',
    title: 'Stretch for 5 minutes',
    category: ActivityCategory.physicalActivity,
    durationMinutes: 5,
    description: 'Gentle full-body stretching — neck, shoulders, back, legs.',
  ),
  ActivationActivity(
    id: 'pa_03',
    title: 'Do 10 jumping jacks',
    category: ActivityCategory.physicalActivity,
    durationMinutes: 2,
    description: 'Quick burst of movement to get your heart rate up.',
  ),
  ActivationActivity(
    id: 'pa_04',
    title: 'Dance to one song',
    category: ActivityCategory.physicalActivity,
    durationMinutes: 4,
    description: 'Put on a favorite song and move however feels good.',
  ),
  ActivationActivity(
    id: 'pa_05',
    title: 'Do a short yoga flow',
    category: ActivityCategory.physicalActivity,
    durationMinutes: 15,
    description: 'Follow a gentle yoga sequence — sun salutations or a beginner flow.',
  ),
  ActivationActivity(
    id: 'pa_06',
    title: '20-min bike ride',
    category: ActivityCategory.physicalActivity,
    durationMinutes: 20,
    description: 'Ride around the neighborhood or on a stationary bike.',
  ),
  ActivationActivity(
    id: 'pa_07',
    title: 'Walk up and down stairs 3 times',
    category: ActivityCategory.physicalActivity,
    durationMinutes: 5,
    description: 'Use any staircase nearby for a quick cardio boost.',
  ),
  ActivationActivity(
    id: 'pa_08',
    title: 'Do 15 push-ups',
    category: ActivityCategory.physicalActivity,
    durationMinutes: 3,
    description: 'Modified or regular — whatever works for your fitness level.',
  ),
  ActivationActivity(
    id: 'pa_09',
    title: 'Follow a 7-min workout video',
    category: ActivityCategory.physicalActivity,
    durationMinutes: 7,
    description: 'Search for a quick bodyweight workout and follow along.',
  ),
  ActivationActivity(
    id: 'pa_10',
    title: 'Do a wall sit for 1 minute',
    category: ActivityCategory.physicalActivity,
    durationMinutes: 2,
    description: 'Lean against a wall in a seated position. Focus on breathing.',
  ),
  ActivationActivity(
    id: 'pa_11',
    title: 'Skip rope for 5 minutes',
    category: ActivityCategory.physicalActivity,
    durationMinutes: 5,
    description: 'Jump rope or pretend to — the movement is what matters.',
  ),
  ActivationActivity(
    id: 'pa_12',
    title: 'Do a plank for 30 seconds',
    category: ActivityCategory.physicalActivity,
    durationMinutes: 2,
    description: 'Hold a plank position on your forearms. Rest and repeat if you like.',
  ),
  ActivationActivity(
    id: 'pa_13',
    title: 'Take a brisk 20-min walk',
    category: ActivityCategory.physicalActivity,
    durationMinutes: 20,
    description: 'Walk at a pace that gets you slightly out of breath.',
  ),

  // ─── Social Connection ───
  ActivationActivity(
    id: 'sc_01',
    title: 'Call a friend',
    category: ActivityCategory.socialConnection,
    durationMinutes: 15,
    description: 'Reach out to someone you care about, even briefly.',
  ),
  ActivationActivity(
    id: 'sc_02',
    title: 'Send a kind text to someone',
    category: ActivityCategory.socialConnection,
    durationMinutes: 3,
    description: 'Text a friend, family member, or colleague something nice.',
  ),
  ActivationActivity(
    id: 'sc_03',
    title: 'Visit a coffee shop',
    category: ActivityCategory.socialConnection,
    durationMinutes: 30,
    description: 'Go sit in a public space. Order a drink and people-watch.',
  ),
  ActivationActivity(
    id: 'sc_04',
    title: 'Write a letter to someone',
    category: ActivityCategory.socialConnection,
    durationMinutes: 20,
    description: 'Handwrite or type a letter to someone you appreciate.',
  ),
  ActivationActivity(
    id: 'sc_05',
    title: 'Video call a family member',
    category: ActivityCategory.socialConnection,
    durationMinutes: 20,
    description: 'Connect face-to-face with someone you haven\'t seen in a while.',
  ),
  ActivationActivity(
    id: 'sc_06',
    title: 'Play with a pet',
    category: ActivityCategory.socialConnection,
    durationMinutes: 15,
    description: 'Spend quality time with your pet — play, cuddle, or walk them.',
  ),
  ActivationActivity(
    id: 'sc_07',
    title: 'Have lunch with someone',
    category: ActivityCategory.socialConnection,
    durationMinutes: 45,
    description: 'Invite a friend or coworker to eat together.',
  ),
  ActivationActivity(
    id: 'sc_08',
    title: 'Reply to a message you\'ve been putting off',
    category: ActivityCategory.socialConnection,
    durationMinutes: 5,
    description: 'Open that conversation and send a reply. It doesn\'t need to be long.',
  ),
  ActivationActivity(
    id: 'sc_09',
    title: 'Compliment a stranger',
    category: ActivityCategory.socialConnection,
    durationMinutes: 1,
    description: 'Tell someone something genuine and positive.',
  ),
  ActivationActivity(
    id: 'sc_10',
    title: 'Join a group chat or forum discussion',
    category: ActivityCategory.socialConnection,
    durationMinutes: 10,
    description: 'Engage with an online community you\'re part of.',
  ),
  ActivationActivity(
    id: 'sc_11',
    title: 'Ask someone how they\'re doing (and listen)',
    category: ActivityCategory.socialConnection,
    durationMinutes: 10,
    description: 'Start a genuine conversation and give someone your full attention.',
  ),
  ActivationActivity(
    id: 'sc_12',
    title: 'Walk with a friend',
    category: ActivityCategory.socialConnection,
    durationMinutes: 30,
    description: 'Combine movement with connection — walk and talk.',
  ),

  // ─── Creative ───
  ActivationActivity(
    id: 'cr_01',
    title: 'Draw or sketch for 15 min',
    category: ActivityCategory.creative,
    durationMinutes: 15,
    description: 'Doodle, sketch an object nearby, or draw from imagination.',
  ),
  ActivationActivity(
    id: 'cr_02',
    title: 'Write a journal entry',
    category: ActivityCategory.creative,
    durationMinutes: 10,
    description: 'Write about your day, feelings, or anything on your mind.',
  ),
  ActivationActivity(
    id: 'cr_03',
    title: 'Photograph something beautiful',
    category: ActivityCategory.creative,
    durationMinutes: 10,
    description: 'Find something visually interesting and capture it with your phone.',
  ),
  ActivationActivity(
    id: 'cr_04',
    title: 'Write a short poem or haiku',
    category: ActivityCategory.creative,
    durationMinutes: 10,
    description: 'Express a feeling or moment in a few carefully chosen lines.',
  ),
  ActivationActivity(
    id: 'cr_05',
    title: 'Color in a coloring book',
    category: ActivityCategory.creative,
    durationMinutes: 20,
    description: 'Use colored pencils, markers, or a digital coloring app.',
  ),
  ActivationActivity(
    id: 'cr_06',
    title: 'Learn a simple origami fold',
    category: ActivityCategory.creative,
    durationMinutes: 15,
    description: 'Follow a tutorial to fold a crane, boat, or flower.',
  ),
  ActivationActivity(
    id: 'cr_07',
    title: 'Play a musical instrument',
    category: ActivityCategory.creative,
    durationMinutes: 15,
    description: 'Play anything you know, or noodle around with sounds.',
  ),
  ActivationActivity(
    id: 'cr_08',
    title: 'Create a playlist for your current mood',
    category: ActivityCategory.creative,
    durationMinutes: 10,
    description: 'Curate 8-10 songs that match or shift how you\'re feeling.',
  ),
  ActivationActivity(
    id: 'cr_09',
    title: 'Write a gratitude list',
    category: ActivityCategory.creative,
    durationMinutes: 5,
    description: 'List 5 things you\'re grateful for right now, big or small.',
  ),
  ActivationActivity(
    id: 'cr_10',
    title: 'Paint with watercolors',
    category: ActivityCategory.creative,
    durationMinutes: 20,
    description: 'No rules — just put color on paper and see what emerges.',
  ),
  ActivationActivity(
    id: 'cr_11',
    title: 'Rearrange or redecorate a shelf',
    category: ActivityCategory.creative,
    durationMinutes: 15,
    description: 'Make a small space look nicer — move objects, add a plant.',
  ),
  ActivationActivity(
    id: 'cr_12',
    title: 'Write a fictional micro-story',
    category: ActivityCategory.creative,
    durationMinutes: 15,
    description: 'Write a story in under 200 words. Any genre, any setting.',
  ),
  ActivationActivity(
    id: 'cr_13',
    title: 'Make a collage from magazines or apps',
    category: ActivityCategory.creative,
    durationMinutes: 20,
    description: 'Cut and arrange images that inspire you or capture a mood.',
  ),

  // ─── Self-Care ───
  ActivationActivity(
    id: 'selfcare_01',
    title: 'Take a warm shower',
    category: ActivityCategory.selfCare,
    durationMinutes: 15,
    description: 'Let warm water relax your muscles. Focus on the sensation.',
  ),
  ActivationActivity(
    id: 'selfcare_02',
    title: 'Drink a full glass of water',
    category: ActivityCategory.selfCare,
    durationMinutes: 2,
    description: 'Hydrate mindfully. Notice the temperature and taste.',
  ),
  ActivationActivity(
    id: 'selfcare_03',
    title: 'Make yourself a cup of tea',
    category: ActivityCategory.selfCare,
    durationMinutes: 10,
    description: 'Boil water, steep tea, and savor it without distractions.',
  ),
  ActivationActivity(
    id: 'selfcare_04',
    title: 'Take a 20-min nap',
    category: ActivityCategory.selfCare,
    durationMinutes: 20,
    description: 'Set a timer and rest. Even lying down with eyes closed helps.',
  ),
  ActivationActivity(
    id: 'selfcare_05',
    title: 'Apply lotion or do skincare',
    category: ActivityCategory.selfCare,
    durationMinutes: 10,
    description: 'Take a few minutes to care for your skin.',
  ),
  ActivationActivity(
    id: 'selfcare_06',
    title: 'Brush and floss your teeth',
    category: ActivityCategory.selfCare,
    durationMinutes: 5,
    description: 'A small act of self-care that boosts how you feel.',
  ),
  ActivationActivity(
    id: 'selfcare_07',
    title: 'Change into clean clothes',
    category: ActivityCategory.selfCare,
    durationMinutes: 5,
    description: 'Put on something fresh. It shifts how you feel physically.',
  ),
  ActivationActivity(
    id: 'selfcare_08',
    title: 'Do a 5-min guided meditation',
    category: ActivityCategory.selfCare,
    durationMinutes: 5,
    description: 'Use an app or simply sit quietly and follow your breath.',
  ),
  ActivationActivity(
    id: 'selfcare_09',
    title: 'Prepare a healthy snack',
    category: ActivityCategory.selfCare,
    durationMinutes: 10,
    description: 'Cut fruit, make trail mix, or prepare something nourishing.',
  ),
  ActivationActivity(
    id: 'selfcare_10',
    title: 'Put on comfortable clothes',
    category: ActivityCategory.selfCare,
    durationMinutes: 3,
    description: 'Change into something soft and cozy.',
  ),
  ActivationActivity(
    id: 'selfcare_11',
    title: 'Massage your hands or feet',
    category: ActivityCategory.selfCare,
    durationMinutes: 5,
    description: 'Apply lotion and gently work out tension in your hands or feet.',
  ),
  ActivationActivity(
    id: 'selfcare_12',
    title: 'Take 10 slow, deep breaths',
    category: ActivityCategory.selfCare,
    durationMinutes: 3,
    description: 'Inhale for 4 counts, hold for 4, exhale for 6. Repeat.',
  ),

  // ─── Productive ───
  ActivationActivity(
    id: 'pr_01',
    title: 'Organize one drawer',
    category: ActivityCategory.productive,
    durationMinutes: 10,
    description: 'Pick one messy drawer and sort through it.',
  ),
  ActivationActivity(
    id: 'pr_02',
    title: 'Clean one surface',
    category: ActivityCategory.productive,
    durationMinutes: 5,
    description: 'Wipe down a counter, desk, or table.',
  ),
  ActivationActivity(
    id: 'pr_03',
    title: 'Do laundry',
    category: ActivityCategory.productive,
    durationMinutes: 15,
    description: 'Start a load of laundry. Fold something while you wait.',
  ),
  ActivationActivity(
    id: 'pr_04',
    title: 'Wash the dishes',
    category: ActivityCategory.productive,
    durationMinutes: 10,
    description: 'Clear your sink. Notice the warmth of the water.',
  ),
  ActivationActivity(
    id: 'pr_05',
    title: 'Make your bed',
    category: ActivityCategory.productive,
    durationMinutes: 3,
    description: 'Straighten sheets and pillows. A small win to start the day.',
  ),
  ActivationActivity(
    id: 'pr_06',
    title: 'Write a to-do list for tomorrow',
    category: ActivityCategory.productive,
    durationMinutes: 5,
    description: 'Plan 3-5 tasks for the next day. Keep it realistic.',
  ),
  ActivationActivity(
    id: 'pr_07',
    title: 'Sort through emails for 10 min',
    category: ActivityCategory.productive,
    durationMinutes: 10,
    description: 'Delete, archive, or respond to what\'s piling up.',
  ),
  ActivationActivity(
    id: 'pr_08',
    title: 'Tidy your desk or workspace',
    category: ActivityCategory.productive,
    durationMinutes: 10,
    description: 'Put things back where they belong. Clear visual clutter.',
  ),
  ActivationActivity(
    id: 'pr_09',
    title: 'Take out the trash',
    category: ActivityCategory.productive,
    durationMinutes: 5,
    description: 'Empty bins around your home. Simple, tangible progress.',
  ),
  ActivationActivity(
    id: 'pr_10',
    title: 'Vacuum or sweep one room',
    category: ActivityCategory.productive,
    durationMinutes: 10,
    description: 'Pick one room and give the floor a quick clean.',
  ),
  ActivationActivity(
    id: 'pr_11',
    title: 'Organize your phone apps',
    category: ActivityCategory.productive,
    durationMinutes: 10,
    description: 'Delete unused apps and organize the rest into folders.',
  ),
  ActivationActivity(
    id: 'pr_12',
    title: 'Pay a bill or handle one admin task',
    category: ActivityCategory.productive,
    durationMinutes: 10,
    description: 'Tackle one small errand you\'ve been avoiding.',
  ),
  ActivationActivity(
    id: 'pr_13',
    title: 'Wipe down bathroom surfaces',
    category: ActivityCategory.productive,
    durationMinutes: 8,
    description: 'Quick clean of the sink, mirror, and counter.',
  ),

  // ─── Leisure ───
  ActivationActivity(
    id: 'le_01',
    title: 'Listen to a full album',
    category: ActivityCategory.leisure,
    durationMinutes: 45,
    description: 'Pick an album and listen start to finish. No skipping.',
  ),
  ActivationActivity(
    id: 'le_02',
    title: 'Read 10 pages of a book',
    category: ActivityCategory.leisure,
    durationMinutes: 15,
    description: 'Pick up any book and read just 10 pages. Fiction or non-fiction.',
  ),
  ActivationActivity(
    id: 'le_03',
    title: 'Watch a short documentary',
    category: ActivityCategory.leisure,
    durationMinutes: 30,
    description: 'Find a 20-30 min documentary on a topic that interests you.',
  ),
  ActivationActivity(
    id: 'le_04',
    title: 'Do a crossword or sudoku puzzle',
    category: ActivityCategory.leisure,
    durationMinutes: 15,
    description: 'Engage your mind with a puzzle. Paper or app.',
  ),
  ActivationActivity(
    id: 'le_05',
    title: 'Try a new recipe',
    category: ActivityCategory.leisure,
    durationMinutes: 45,
    description: 'Find a simple recipe you haven\'t made before and cook it.',
  ),
  ActivationActivity(
    id: 'le_06',
    title: 'Cook a simple meal',
    category: ActivityCategory.leisure,
    durationMinutes: 30,
    description: 'Make something from scratch — even a sandwich counts.',
  ),
  ActivationActivity(
    id: 'le_07',
    title: 'Browse a bookstore or library',
    category: ActivityCategory.leisure,
    durationMinutes: 30,
    description: 'Walk around, pick up books, read back covers.',
  ),
  ActivationActivity(
    id: 'le_08',
    title: 'Listen to a podcast episode',
    category: ActivityCategory.leisure,
    durationMinutes: 30,
    description: 'Pick an episode on a topic you enjoy and listen fully.',
  ),
  ActivationActivity(
    id: 'le_09',
    title: 'Play a board game or card game',
    category: ActivityCategory.leisure,
    durationMinutes: 30,
    description: 'Play solitaire, or invite someone for a game.',
  ),
  ActivationActivity(
    id: 'le_10',
    title: 'Watch a comedy special',
    category: ActivityCategory.leisure,
    durationMinutes: 45,
    description: 'Put on a stand-up special and let yourself laugh.',
  ),
  ActivationActivity(
    id: 'le_11',
    title: 'Build something with Lego or blocks',
    category: ActivityCategory.leisure,
    durationMinutes: 20,
    description: 'Follow instructions or build freely. Focus on the process.',
  ),
  ActivationActivity(
    id: 'le_12',
    title: 'Learn one fun fact about a topic',
    category: ActivityCategory.leisure,
    durationMinutes: 10,
    description: 'Search something you\'re curious about and read one article.',
  ),
  ActivationActivity(
    id: 'le_13',
    title: 'Solve a brain teaser',
    category: ActivityCategory.leisure,
    durationMinutes: 10,
    description: 'Find a riddle or logic puzzle and work through it.',
  ),

  // ─── Routine ───
  ActivationActivity(
    id: 'ro_01',
    title: 'Eat a proper breakfast',
    category: ActivityCategory.routine,
    durationMinutes: 15,
    description: 'Sit down and eat — not on the go, not in bed.',
  ),
  ActivationActivity(
    id: 'ro_02',
    title: 'Set an alarm and wake on time',
    category: ActivityCategory.routine,
    durationMinutes: 1,
    description: 'Set your alarm for a consistent wake time tonight.',
  ),
  ActivationActivity(
    id: 'ro_03',
    title: 'Shower and get dressed',
    category: ActivityCategory.routine,
    durationMinutes: 20,
    description: 'Full shower and change into day clothes, even if staying home.',
  ),
  ActivationActivity(
    id: 'ro_04',
    title: 'Prepare lunch or dinner',
    category: ActivityCategory.routine,
    durationMinutes: 30,
    description: 'Cook a meal. Following a recipe counts.',
  ),
  ActivationActivity(
    id: 'ro_05',
    title: 'Go to bed at a set time',
    category: ActivityCategory.routine,
    durationMinutes: 5,
    description: 'Start your wind-down routine at the same time each night.',
  ),
  ActivationActivity(
    id: 'ro_06',
    title: 'Plan your meals for tomorrow',
    category: ActivityCategory.routine,
    durationMinutes: 10,
    description: 'Decide what you\'ll eat for each meal tomorrow.',
  ),
  ActivationActivity(
    id: 'ro_07',
    title: 'Do a morning routine checklist',
    category: ActivityCategory.routine,
    durationMinutes: 15,
    description: 'Wake, hydrate, hygiene, get dressed, eat. Check each off.',
  ),
  ActivationActivity(
    id: 'ro_08',
    title: 'Set out clothes for tomorrow',
    category: ActivityCategory.routine,
    durationMinutes: 5,
    description: 'Pick what you\'ll wear and lay it out before bed.',
  ),
  ActivationActivity(
    id: 'ro_09',
    title: 'Grocery shop for the week',
    category: ActivityCategory.routine,
    durationMinutes: 45,
    description: 'Make a list and get what you need for the next few days.',
  ),
  ActivationActivity(
    id: 'ro_10',
    title: 'Water your plants',
    category: ActivityCategory.routine,
    durationMinutes: 5,
    description: 'Check on your plants, water the dry ones, trim dead leaves.',
  ),
  ActivationActivity(
    id: 'ro_11',
    title: 'Wind-down routine before bed',
    category: ActivityCategory.routine,
    durationMinutes: 20,
    description: 'Dim lights, put away screens, read or stretch.',
  ),
  ActivationActivity(
    id: 'ro_12',
    title: 'Take any daily vitamins or medication',
    category: ActivityCategory.routine,
    durationMinutes: 1,
    description: 'Don\'t skip — consistency matters.',
  ),
  ActivationActivity(
    id: 'ro_13',
    title: 'Pack your bag for tomorrow',
    category: ActivityCategory.routine,
    durationMinutes: 5,
    description: 'Prepare everything you need before you leave the house.',
  ),

  // ─── Nature ───
  ActivationActivity(
    id: 'na_01',
    title: 'Go outside for 5 minutes',
    category: ActivityCategory.nature,
    durationMinutes: 5,
    description: 'Step outside and just be. Feel the air on your skin.',
  ),
  ActivationActivity(
    id: 'na_02',
    title: 'Sit in a park for 15 min',
    category: ActivityCategory.nature,
    durationMinutes: 15,
    description: 'Find a bench or patch of grass and sit without your phone.',
  ),
  ActivationActivity(
    id: 'na_03',
    title: 'Watch the sunrise or sunset',
    category: ActivityCategory.nature,
    durationMinutes: 15,
    description: 'Find a spot with a view and watch the sky change.',
  ),
  ActivationActivity(
    id: 'na_04',
    title: 'Walk barefoot on grass',
    category: ActivityCategory.nature,
    durationMinutes: 5,
    description: 'Grounding exercise — feel the earth under your feet.',
  ),
  ActivationActivity(
    id: 'na_05',
    title: 'Listen to birds for 5 minutes',
    category: ActivityCategory.nature,
    durationMinutes: 5,
    description: 'Go outside or open a window. Focus only on bird sounds.',
  ),
  ActivationActivity(
    id: 'na_06',
    title: 'Take a nature photo walk',
    category: ActivityCategory.nature,
    durationMinutes: 20,
    description: 'Walk around and photograph plants, sky, textures in nature.',
  ),
  ActivationActivity(
    id: 'na_07',
    title: 'Tend a garden or repot a plant',
    category: ActivityCategory.nature,
    durationMinutes: 20,
    description: 'Get your hands in soil. Trim, water, or transplant.',
  ),
  ActivationActivity(
    id: 'na_08',
    title: 'Watch clouds for 10 minutes',
    category: ActivityCategory.nature,
    durationMinutes: 10,
    description: 'Lie down or sit back and just watch the sky move.',
  ),
  ActivationActivity(
    id: 'na_09',
    title: 'Walk a nature trail',
    category: ActivityCategory.nature,
    durationMinutes: 30,
    description: 'Find a local trail or green area and walk through it.',
  ),
  ActivationActivity(
    id: 'na_10',
    title: 'Open a window and breathe fresh air',
    category: ActivityCategory.nature,
    durationMinutes: 3,
    description: 'Open a window wide. Take several deep breaths of outside air.',
  ),
  ActivationActivity(
    id: 'na_11',
    title: 'Eat a meal outside',
    category: ActivityCategory.nature,
    durationMinutes: 20,
    description: 'Take your plate to a balcony, porch, or park bench.',
  ),
  ActivationActivity(
    id: 'na_12',
    title: 'Collect interesting leaves or stones',
    category: ActivityCategory.nature,
    durationMinutes: 15,
    description: 'Walk around and pick up natural objects that catch your eye.',
  ),
  ActivationActivity(
    id: 'na_13',
    title: 'Stargaze for 10 minutes',
    category: ActivityCategory.nature,
    durationMinutes: 10,
    description: 'On a clear night, go outside and look up at the stars.',
  ),
];

List<ActivationActivity> activitiesByCategory(ActivityCategory category) =>
    activityPool.where((a) => a.category == category).toList();

String activityCategoryLabel(ActivityCategory c) => switch (c) {
      ActivityCategory.physicalActivity => 'Physical',
      ActivityCategory.socialConnection => 'Social',
      ActivityCategory.creative => 'Creative',
      ActivityCategory.selfCare => 'Self-Care',
      ActivityCategory.productive => 'Productive',
      ActivityCategory.leisure => 'Leisure',
      ActivityCategory.routine => 'Routine',
      ActivityCategory.nature => 'Nature',
    };

IconData activityCategoryIcon(ActivityCategory c) {
  // Returns a string name; the presentation layer maps to actual IconData.
  return switch (c) {
    ActivityCategory.physicalActivity => const IconData(0xe3ac, fontFamily: 'MaterialIcons'), // directions_run
    ActivityCategory.socialConnection => const IconData(0xe491, fontFamily: 'MaterialIcons'), // people
    ActivityCategory.creative => const IconData(0xe3ae, fontFamily: 'MaterialIcons'), // palette
    ActivityCategory.selfCare => const IconData(0xf0504, fontFamily: 'MaterialIcons'), // spa
    ActivityCategory.productive => const IconData(0xe179, fontFamily: 'MaterialIcons'), // checklist
    ActivityCategory.leisure => const IconData(0xe1bd, fontFamily: 'MaterialIcons'), // local_cafe
    ActivityCategory.routine => const IconData(0xe616, fontFamily: 'MaterialIcons'), // schedule
    ActivityCategory.nature => const IconData(0xe3be, fontFamily: 'MaterialIcons'), // park
  };
}
