const List<String> dailyInsights = [
  'Small choices add up. Even a 2-minute reset builds your pattern.',
  'Your support windows become clearer with every check-in.',
  'Sleep quality improves when you protect your evening routine.',
  'How you respond after a reset moment builds your strongest protection.',
  'Boredom opens the door to old patterns. Having a go-to reset ready helps.',
  'Each protected moment is building new pathways.',
  'People who check in daily see their patterns clearly within weeks.',
  'Awareness of what triggers you is already half the protection.',
  'Morning routines that skip the phone for 20 minutes protect the whole day.',
  'Confidence comes from knowing you can pause and choose differently.',
  'Each small awareness moment literally strengthens your prefrontal cortex.',
  'Social connection is a powerful alternative to old patterns. Reach out today.',
  'Your recovery momentum builds slowly at first, then steadily.',
  'Breaking a loop once makes it easier to pause the next time.',
  'Late-night phone use is worth protecting against. Charge your phone outside the bedroom.',
  'Physical exercise for just 20 minutes helps clear the mind.',
  'Noticing what helped today strengthens your awareness for tomorrow.',
  'Your patterns are becoming clearer. That is real progress.',
  'Most people overestimate week one and underestimate how steady week four feels.',
  'Your awareness is like a muscle. Every day it gets stronger.',
  'People who name their top 3 triggers see their patterns more clearly.',
  'Cold water on your face can break an automatic loop in 30 seconds.',
  'A short reflection before bed reduces next-day stress.',
  'Growth is not a straight line. A tough day does not erase a steady week.',
  'The hardest part is not changing one habit. It is building a life you do not need to escape.',
  'Deep breathing for 2 minutes shifts your nervous system toward calm.',
  'Your brain is forming new pathways right now. Every steady choice counts.',
  'You are already building accountability by using this app.',
  'Self-compassion after a reset moment leads to faster learning.',
  'The version of you in 12 weeks will thank the version choosing now.',
  'Mindful awareness of a loop without acting on it is your strongest support skill.',
];
